"""initial schema

Hand-written rather than autogenerated so the emitted DDL matches schema.sql
literally, index names included. Plain SQLAlchemy types are used instead of the
application TypeDecorators: a migration must keep working even if those are
renamed later.

Revision ID: 0001
Revises:
Create Date: 2026-07-27

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "sets",
        sa.Column("set_num", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("theme", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("pieces", sa.Integer(), nullable=True),
        sa.Column("rrp_eur", sa.REAL(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("set_num", name="pk_sets"),
    )
    op.create_index("idx_sets_name_normalized", "sets", ["name_normalized"])
    op.create_index("idx_sets_theme", "sets", ["theme"])

    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("set_num", sa.Text(), nullable=True),
        sa.Column("resolution_score", sa.REAL(), nullable=True),
        sa.Column("resolution_method", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("merchant", sa.Text(), nullable=True),
        sa.Column("title_raw", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("current_price_eur", sa.REAL(), nullable=True),
        sa.Column("first_seen_at", sa.Text(), nullable=False),
        sa.Column("last_seen_at", sa.Text(), nullable=False),
        sa.Column(
            "is_active", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["set_num"], ["sets.set_num"], name="fk_offers_set_num_sets"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_offers"),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_offers_source_external_id"
        ),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_offers_set_num", "offers", ["set_num"])
    op.create_index("idx_offers_active", "offers", ["is_active", "last_seen_at"])

    op.create_table(
        "price_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column("price_eur", sa.REAL(), nullable=False),
        sa.Column("observed_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"], ["offers.id"], name="fk_price_points_offer_id_offers"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_price_points"),
        sqlite_autoincrement=True,
    )
    op.create_index(
        "idx_price_points_offer", "price_points", ["offer_id", "observed_at"]
    )

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.Text(), nullable=False),
        sa.Column("price_eur", sa.REAL(), nullable=False),
        sa.Column("discount_pct", sa.REAL(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"], ["offers.id"], name="fk_alerts_offer_id_offers"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_alerts"),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_alerts_offer", "alerts", ["offer_id", "sent_at"])

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column(
            "items_found", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "items_new", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "items_resolved", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "alerts_sent", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_runs"),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_runs_source", "runs", ["source", "started_at"])


def downgrade() -> None:
    op.drop_index("idx_runs_source", table_name="runs")
    op.drop_table("runs")
    op.drop_index("idx_alerts_offer", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("idx_price_points_offer", table_name="price_points")
    op.drop_table("price_points")
    op.drop_index("idx_offers_active", table_name="offers")
    op.drop_index("idx_offers_set_num", table_name="offers")
    op.drop_table("offers")
    op.drop_index("idx_sets_theme", table_name="sets")
    op.drop_index("idx_sets_name_normalized", table_name="sets")
    op.drop_table("sets")
