"""health alerts

Hand-written rather than autogenerated, like 0001, so the emitted DDL matches
schema.sql literally. Plain SQLAlchemy types instead of the application
TypeDecorators: a migration must keep working even if those are renamed.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-29

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "health_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_health_alerts"),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_health_alerts_source", "health_alerts", ["source", "sent_at"])


def downgrade() -> None:
    op.drop_index("idx_health_alerts_source", table_name="health_alerts")
    op.drop_table("health_alerts")
